#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =
CFLAGS = -Wall -std=c++14 `pkg-config --cflags gtk+-3.0 gmodule-2.0` -rdynamic
RESINC =
LIBDIR =
LIB =
LDFLAGS = `pkg-config --libs gtk+-3.0 gmodule-2.0`

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -Wall -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG =
OUT_DEBUG = bin/Debug/GNOME-Shortcut-Manager

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE =
OUT_RELEASE = bin/Release/GNOME-Shortcut-Manager

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/AboutWindow/aboutwindow.o $(OBJDIR_DEBUG)/src/FileManager/filemanager.o $(OBJDIR_DEBUG)/src/FilePicker/filepicker.o $(OBJDIR_DEBUG)/src/MainWindow/mainwindow.o $(OBJDIR_DEBUG)/src/main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/AboutWindow/aboutwindow.o $(OBJDIR_RELEASE)/src/FileManager/filemanager.o $(OBJDIR_RELEASE)/src/FilePicker/filepicker.o $(OBJDIR_RELEASE)/src/MainWindow/mainwindow.o $(OBJDIR_RELEASE)/src/main.o

all: debug release

clean: clean_debug clean_release

before_debug:
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/AboutWindow || mkdir -p $(OBJDIR_DEBUG)/src/AboutWindow
	test -d $(OBJDIR_DEBUG)/src/FileManager || mkdir -p $(OBJDIR_DEBUG)/src/FileManager
	test -d $(OBJDIR_DEBUG)/src/FilePicker || mkdir -p $(OBJDIR_DEBUG)/src/FilePicker
	test -d $(OBJDIR_DEBUG)/src/MainWindow || mkdir -p $(OBJDIR_DEBUG)/src/MainWindow
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug:

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/AboutWindow/aboutwindow.o: src/AboutWindow/aboutwindow.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/AboutWindow/aboutwindow.cpp -o $(OBJDIR_DEBUG)/src/AboutWindow/aboutwindow.o

$(OBJDIR_DEBUG)/src/FileManager/filemanager.o: src/FileManager/filemanager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/FileManager/filemanager.cpp -o $(OBJDIR_DEBUG)/src/FileManager/filemanager.o

$(OBJDIR_DEBUG)/src/FilePicker/filepicker.o: src/FilePicker/filepicker.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/FilePicker/filepicker.cpp -o $(OBJDIR_DEBUG)/src/FilePicker/filepicker.o

$(OBJDIR_DEBUG)/src/MainWindow/mainwindow.o: src/MainWindow/mainwindow.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/MainWindow/mainwindow.cpp -o $(OBJDIR_DEBUG)/src/MainWindow/mainwindow.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

clean_debug:
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/AboutWindow
	rm -rf $(OBJDIR_DEBUG)/src/FileManager
	rm -rf $(OBJDIR_DEBUG)/src/FilePicker
	rm -rf $(OBJDIR_DEBUG)/src/MainWindow
	rm -rf $(OBJDIR_DEBUG)/src

before_release:
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src/AboutWindow || mkdir -p $(OBJDIR_RELEASE)/src/AboutWindow
	test -d $(OBJDIR_RELEASE)/src/FileManager || mkdir -p $(OBJDIR_RELEASE)/src/FileManager
	test -d $(OBJDIR_RELEASE)/src/FilePicker || mkdir -p $(OBJDIR_RELEASE)/src/FilePicker
	test -d $(OBJDIR_RELEASE)/src/MainWindow || mkdir -p $(OBJDIR_RELEASE)/src/MainWindow
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release:

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/AboutWindow/aboutwindow.o: src/AboutWindow/aboutwindow.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/AboutWindow/aboutwindow.cpp -o $(OBJDIR_RELEASE)/src/AboutWindow/aboutwindow.o

$(OBJDIR_RELEASE)/src/FileManager/filemanager.o: src/FileManager/filemanager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/FileManager/filemanager.cpp -o $(OBJDIR_RELEASE)/src/FileManager/filemanager.o

$(OBJDIR_RELEASE)/src/FilePicker/filepicker.o: src/FilePicker/filepicker.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/FilePicker/filepicker.cpp -o $(OBJDIR_RELEASE)/src/FilePicker/filepicker.o

$(OBJDIR_RELEASE)/src/MainWindow/mainwindow.o: src/MainWindow/mainwindow.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/MainWindow/mainwindow.cpp -o $(OBJDIR_RELEASE)/src/MainWindow/mainwindow.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

clean_release:
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src/AboutWindow
	rm -rf $(OBJDIR_RELEASE)/src/FileManager
	rm -rf $(OBJDIR_RELEASE)/src/FilePicker
	rm -rf $(OBJDIR_RELEASE)/src/MainWindow
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release
